name: Watchdog
description: Stop the server when it hangs
author: StarTux
version: 0.1
main: com.winthier.watchdog.bukkit.BukkitWatchdogPlugin
depend: []
commands:
  watchdog:
    description: Admin interface
    permission: watchdog.watchdog
    usage: /<command> cancel|tick
permissions:
  watchdog.watchdog:
    description: use the /watchdog command
    default: op
